use crate::ast::{Query, QueryFile};

pub fn generate_sql(query_file: &QueryFile) -> String {
    let mut output = String::new();
    output.push_str("-- Generated SQL queries\n");
    output.push_str("-- DO NOT EDIT - Auto-generated by Stratus\n\n");

    for query in &query_file.queries {
        output.push_str(&format!("-- name: {}\n", query.name));
        output.push_str(&format!("-- params: {:?}\n", query.params));
        output.push_str(&format!("-- return: {}\n", query.return_type));
        output.push_str(&query.sql);
        output.push_str("\n\n");
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Param, Query, QueryFile};

    #[test]
    fn test_generate_sql() {
        let qf = QueryFile {
            queries: vec![Query {
                name: "GetUser".to_string(),
                return_type: "one".to_string(),
                sql: "SELECT * FROM users WHERE id = $1;".to_string(),
                params: vec![Param {
                    name: "id".to_string(),
                    type_: "number".to_string(),
                    ordinal: 1,
                }],
            }],
        };

        let result = generate_sql(&qf);
        assert!(result.contains("-- name: GetUser"));
        assert!(result.contains("SELECT * FROM users WHERE id = $1;"));
    }
}
